### ISSUE TITLE
hoe to install :(

### ISSUE THREAD

**Issue by retrievaaaa** [GoombaProgrammer/cqx96#1]
hoiw tekll me you dug

**Comment by Imusing** [comment]
Use a virtual machine (or a USB or a floppy) and boot it.

You can install to a hard drive but that is buggy.

**Comment by retrievaaaa** [comment]
oooook but where download :( @GoombaProgrammer

**Comment by Imusing** [comment]
> oooook but where download :( @GoombaProgrammer

You need to compile it

**Comment by retrievaaaa** [comment]
how u cvuent
